[package]
name = "saberrs"
version = "0.1.0"
authors = ["Franck Parat <franck.parat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
